# Generated by Django 3.1.1 on 2020-10-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageModel',
            new_name='UserInterfacePage',
        ),
    ]
