# Generated by Django 3.1.1 on 2020-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201026_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterfacepage',
            name='summary_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
