# Generated by Django 3.1.1 on 2020-10-27 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201027_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterfacepage',
            name='benefactors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=20),
        ),
    ]
