# Generated by Django 3.1.1 on 2020-10-28 20:59

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201028_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_logo', models.ImageField(null=True, upload_to='')),
                ('company_homepage_URL', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinterfacepage',
            name='sponsors_images',
        ),
        migrations.AddField(
            model_name='userinterfacepage',
            name='benefactors',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='userinterfacepage',
            name='club_sponsors',
            field=models.ManyToManyField(to='home.Sponsor'),
        ),
    ]
