# Generated by Django 3.1.1 on 2020-10-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201029_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInterfacePage',
            new_name='HomePageContent',
        ),
    ]
