# Generated by Django 3.1.1 on 2020-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201029_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
