# Generated by Django 3.1.1 on 2020-10-30 17:42

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201029_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='benefactors',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=70), null=True, size=None),
        ),
    ]
