# Generated by Django 3.1.1 on 2020-12-07 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201030_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='summary_introduction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
