# Generated by Django 3.1.1 on 2021-03-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201207_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='last_modified',
        ),
    ]
