# Generated by Django 3.1.1 on 2020-11-11 13:58

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=70), null=True, size=None)),
            ],
        ),
    ]
