# Generated by Django 3.1.1 on 2020-11-11 14:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentspagecontent',
            name='policies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
    ]
