# Generated by Django 3.1.1 on 2020-11-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201111_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentspagecontent',
            name='policies',
        ),
        migrations.AddField(
            model_name='documentspagecontent',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('display_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documentspagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('display_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documentspagecontent')),
            ],
        ),
    ]
