# Generated by Django 3.1.1 on 2020-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20201111_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='document_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policydocument',
            name='document_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
