# Generated by Django 3.1.1 on 2020-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=254)),
            ],
        ),
    ]
