# Generated by Django 3.1.1 on 2021-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='description',
            field=models.TextField(),
        ),
    ]
