# Generated by Django 3.1.1 on 2021-03-10 19:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210310_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
