# Generated by Django 3.1.1 on 2021-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210310_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
