# Generated by Django 3.1.1 on 2021-03-14 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210310_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
